# Generated by Django 4.2.3 on 2023-07-14 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='answer_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='question_images/')),
                ('penalty', models.IntegerField(help_text='Штрафное время в секундах')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close'), ('IN_PROGRESS', 'In Progress'), ('DISABLED', 'Disabled')], default='OPEN', max_length=12)),
                ('cell_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.celltype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.field')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'ordering': ['field_number'],
            },
        ),
    ]
