# Generated by Django 4.2.3 on 2023-07-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
